services:
  launchops-mysql:
    image: mysql:8.4
    container_name: launchops-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: launchops_control_tower
    ports:
      - "3306:3306"
    volumes:
      - launchops_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  launchops_mysql_data:
